// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: squareline_empleados_v2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PantallaPendientes
void ui_PantallaPendientes_screen_init(void);
lv_obj_t * ui_PantallaPendientes;
lv_obj_t * ui_ContPanelPrincial;
lv_obj_t * ui_ContPanelPBar;
lv_obj_t * ui_LblPendietes;
void ui_event_BtnTareasExtras(lv_event_t * e);
lv_obj_t * ui_BtnTareasExtras;
lv_obj_t * ui_ContPContenido;
void ui_event_BtnCompletarTarea(lv_event_t * e);
lv_obj_t * ui_BtnCompletarTarea;
lv_obj_t * ui_LblBtnCampletarTarea;
lv_obj_t * ui_ContInformacionReloj;
lv_obj_t * ui_BateriaBar;
lv_obj_t * ui_BateriaLabel;
lv_obj_t * ui_Reloj;
lv_obj_t * ui_ContAnimacionDeCarga;
lv_obj_t * ui_SpinnerCargando;
lv_obj_t * ui_labelCargando;
// CUSTOM VARIABLES

// SCREEN: ui_PantallaTareasExtras
void ui_PantallaTareasExtras_screen_init(void);
lv_obj_t * ui_PantallaTareasExtras;
lv_obj_t * ui_ContTareasExtras;
lv_obj_t * ui_ContTEBar;
void ui_event_BtnPendientes(lv_event_t * e);
lv_obj_t * ui_BtnPendientes;
lv_obj_t * ui_lblTareasExtras;
lv_obj_t * ui_ContTEContenido;
lv_obj_t * ui_btnPrueba1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_btnPrueba;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
void ui_event_BtnCompletarTareaExtra(lv_event_t * e);
lv_obj_t * ui_BtnCompletarTareaExtra;
lv_obj_t * ui_LblBtnCampletarTarea3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BtnTareasExtras(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AbrirTareasExtras(e);
    }
}

void ui_event_BtnCompletarTarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        completarTarea(e);
    }
}

void ui_event_BtnPendientes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AbrirPendientes(e);
    }
}

void ui_event_BtnCompletarTareaExtra(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        completarTareaExtra(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PantallaPendientes_screen_init();
    ui_PantallaTareasExtras_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PantallaPendientes);
}
