// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: squareline_empleados_v2

#ifndef _SQUARELINE_EMPLEADOS_V2_UI_H
#define _SQUARELINE_EMPLEADOS_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_PantallaPendientes
void ui_PantallaPendientes_screen_init(void);
extern lv_obj_t * ui_PantallaPendientes;
extern lv_obj_t * ui_ContPanelPrincial;
extern lv_obj_t * ui_ContPanelPBar;
extern lv_obj_t * ui_LblPendietes;
void ui_event_BtnTareasExtras(lv_event_t * e);
extern lv_obj_t * ui_BtnTareasExtras;
extern lv_obj_t * ui_ContPContenido;
void ui_event_BtnCompletarTarea(lv_event_t * e);
extern lv_obj_t * ui_BtnCompletarTarea;
extern lv_obj_t * ui_LblBtnCampletarTarea;
extern lv_obj_t * ui_ContInformacionReloj;
extern lv_obj_t * ui_BateriaBar;
extern lv_obj_t * ui_BateriaLabel;
extern lv_obj_t * ui_Reloj;
extern lv_obj_t * ui_ContAnimacionDeCarga;
extern lv_obj_t * ui_SpinnerCargando;
extern lv_obj_t * ui_labelCargando;
// CUSTOM VARIABLES

// SCREEN: ui_PantallaTareasExtras
void ui_PantallaTareasExtras_screen_init(void);
extern lv_obj_t * ui_PantallaTareasExtras;
extern lv_obj_t * ui_ContTareasExtras;
extern lv_obj_t * ui_ContTEBar;
void ui_event_BtnPendientes(lv_event_t * e);
extern lv_obj_t * ui_BtnPendientes;
extern lv_obj_t * ui_lblTareasExtras;
extern lv_obj_t * ui_ContTEContenido;
extern lv_obj_t * ui_btnPrueba1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_btnPrueba;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
void ui_event_BtnCompletarTareaExtra(lv_event_t * e);
extern lv_obj_t * ui_BtnCompletarTareaExtra;
extern lv_obj_t * ui_LblBtnCampletarTarea3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_agregartarea50_png);    // assets/agregarTarea50.png
LV_IMG_DECLARE(ui_img_flecha50_png);    // assets/flecha50.png

// FONTS
LV_FONT_DECLARE(ui_font_ArialRounded);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
