// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: squareline_empleados_v2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void AbrirTareasExtras(lv_event_t * e);
void completarTarea(lv_event_t * e);
void AbrirPendientes(lv_event_t * e);
void completarTareaExtra(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
