// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: squareline_empleados_v2

#include "ui.h"

void ui_PantallaPendientes_screen_init(void)
{
    ui_PantallaPendientes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PantallaPendientes,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PantallaPendientes, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PantallaPendientes, LV_DIR_HOR);
    lv_obj_set_scroll_snap_y(ui_PantallaPendientes, LV_SCROLL_SNAP_CENTER);

    ui_ContPanelPrincial = lv_obj_create(ui_PantallaPendientes);
    lv_obj_remove_style_all(ui_ContPanelPrincial);
    lv_obj_set_width(ui_ContPanelPrincial, 240);
    lv_obj_set_height(ui_ContPanelPrincial, 220);
    lv_obj_set_align(ui_ContPanelPrincial, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ContPanelPrincial, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContPanelPrincial, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContPanelPrincial,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContPanelPrincial, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_ContPanelPrincial, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_ContPanelPrincial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContPanelPrincial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ContPanelPrincial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContPanelPrincial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContPanelPrincial, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContPanelPBar = lv_obj_create(ui_ContPanelPrincial);
    lv_obj_remove_style_all(ui_ContPanelPBar);
    lv_obj_set_width(ui_ContPanelPBar, 240);
    lv_obj_set_height(ui_ContPanelPBar, 60);
    lv_obj_set_x(ui_ContPanelPBar, 0);
    lv_obj_set_y(ui_ContPanelPBar, 28);
    lv_obj_set_align(ui_ContPanelPBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContPanelPBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContPanelPBar, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContPanelPBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContPanelPBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContPanelPBar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPendietes = lv_label_create(ui_ContPanelPBar);
    lv_obj_set_width(ui_LblPendietes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPendietes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPendietes, -50);
    lv_obj_set_y(ui_LblPendietes, 0);
    lv_obj_set_align(ui_LblPendietes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPendietes, "tareas no\ncompletadas");
    lv_obj_set_style_text_font(ui_LblPendietes, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnTareasExtras = lv_btn_create(ui_ContPanelPBar);
    lv_obj_set_width(ui_BtnTareasExtras, 50);
    lv_obj_set_height(ui_BtnTareasExtras, 50);
    lv_obj_set_x(ui_BtnTareasExtras, 0);
    lv_obj_set_y(ui_BtnTareasExtras, 4);
    lv_obj_set_align(ui_BtnTareasExtras, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnTareasExtras, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTareasExtras, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnTareasExtras, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTareasExtras, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTareasExtras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnTareasExtras, &ui_img_agregartarea50_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContPContenido = lv_obj_create(ui_ContPanelPrincial);
    lv_obj_remove_style_all(ui_ContPContenido);
    lv_obj_set_width(ui_ContPContenido, 240);
    lv_obj_set_height(ui_ContPContenido, 160);
    lv_obj_set_align(ui_ContPContenido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContPContenido, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContPContenido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_ContPContenido, LV_DIR_VER);
    lv_obj_set_style_pad_row(ui_ContPContenido, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContPContenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCompletarTarea = lv_btn_create(ui_ContPanelPrincial);
    lv_obj_set_width(ui_BtnCompletarTarea, 240);
    lv_obj_set_height(ui_BtnCompletarTarea, 40);
    lv_obj_set_align(ui_BtnCompletarTarea, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnCompletarTarea, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BtnCompletarTarea,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BtnCompletarTarea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblBtnCampletarTarea = lv_label_create(ui_BtnCompletarTarea);
    lv_obj_set_width(ui_LblBtnCampletarTarea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblBtnCampletarTarea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblBtnCampletarTarea, -1);
    lv_obj_set_y(ui_LblBtnCampletarTarea, 1);
    lv_obj_set_align(ui_LblBtnCampletarTarea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblBtnCampletarTarea, "TAREA COMPLETADA");

    ui_ContInformacionReloj = lv_obj_create(ui_PantallaPendientes);
    lv_obj_remove_style_all(ui_ContInformacionReloj);
    lv_obj_set_width(ui_ContInformacionReloj, 240);
    lv_obj_set_height(ui_ContInformacionReloj, 20);
    lv_obj_set_align(ui_ContInformacionReloj, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContInformacionReloj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContInformacionReloj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContInformacionReloj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BateriaBar = lv_bar_create(ui_ContInformacionReloj);
    lv_bar_set_value(ui_BateriaBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BateriaBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BateriaBar, 64);
    lv_obj_set_height(ui_BateriaBar, 13);
    lv_obj_set_x(ui_BateriaBar, 86);
    lv_obj_set_y(ui_BateriaBar, 0);
    lv_obj_set_align(ui_BateriaBar, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_BateriaBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BateriaBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BateriaBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BateriaLabel = lv_label_create(ui_ContInformacionReloj);
    lv_obj_set_width(ui_BateriaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BateriaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BateriaLabel, 30);
    lv_obj_set_y(ui_BateriaLabel, 0);
    lv_obj_set_align(ui_BateriaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BateriaLabel, "10%");
    lv_obj_set_style_text_font(ui_BateriaLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Reloj = lv_label_create(ui_ContInformacionReloj);
    lv_obj_set_width(ui_Reloj, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Reloj, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Reloj, -82);
    lv_obj_set_y(ui_Reloj, 0);
    lv_obj_set_align(ui_Reloj, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Reloj, "10:50");
    lv_obj_clear_flag(ui_Reloj, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Reloj, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContAnimacionDeCarga = lv_obj_create(ui_PantallaPendientes);
    lv_obj_remove_style_all(ui_ContAnimacionDeCarga);
    lv_obj_set_width(ui_ContAnimacionDeCarga, 240);
    lv_obj_set_height(ui_ContAnimacionDeCarga, 220);
    lv_obj_set_align(ui_ContAnimacionDeCarga, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ContAnimacionDeCarga, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContAnimacionDeCarga, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContAnimacionDeCarga, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContAnimacionDeCarga, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContAnimacionDeCarga, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContAnimacionDeCarga, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SpinnerCargando = lv_spinner_create(ui_ContAnimacionDeCarga, 1000, 90);
    lv_obj_set_width(ui_SpinnerCargando, 120);
    lv_obj_set_height(ui_SpinnerCargando, 120);
    lv_obj_set_align(ui_SpinnerCargando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerCargando, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SpinnerCargando, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinnerCargando, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerCargando, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerCargando, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerCargando, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_labelCargando = lv_label_create(ui_ContAnimacionDeCarga);
    lv_obj_set_width(ui_labelCargando, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCargando, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCargando, 0);
    lv_obj_set_y(ui_labelCargando, 80);
    lv_obj_set_align(ui_labelCargando, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCargando, "CARGANDO");
    lv_obj_set_style_text_font(ui_labelCargando, &ui_font_ArialRounded, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnTareasExtras, ui_event_BtnTareasExtras, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCompletarTarea, ui_event_BtnCompletarTarea, LV_EVENT_ALL, NULL);

}
