// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: squareline_empleados_v2

#include "ui.h"

void ui_PantallaTareasExtras_screen_init(void)
{
    ui_PantallaTareasExtras = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PantallaTareasExtras, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContTareasExtras = lv_obj_create(ui_PantallaTareasExtras);
    lv_obj_remove_style_all(ui_ContTareasExtras);
    lv_obj_set_width(ui_ContTareasExtras, 240);
    lv_obj_set_height(ui_ContTareasExtras, 220);
    lv_obj_set_align(ui_ContTareasExtras, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ContTareasExtras, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContTareasExtras, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContTareasExtras,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContTareasExtras, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ContTareasExtras, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_ContTareasExtras, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContTareasExtras, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ContTareasExtras, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContTareasExtras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContTareasExtras, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContTEBar = lv_obj_create(ui_ContTareasExtras);
    lv_obj_remove_style_all(ui_ContTEBar);
    lv_obj_set_width(ui_ContTEBar, 240);
    lv_obj_set_height(ui_ContTEBar, 60);
    lv_obj_set_x(ui_ContTEBar, 43);
    lv_obj_set_y(ui_ContTEBar, -12);
    lv_obj_set_align(ui_ContTEBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContTEBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContTEBar, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContTEBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContTEBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContTEBar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContTEBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContTEBar, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPendientes = lv_btn_create(ui_ContTEBar);
    lv_obj_set_width(ui_BtnPendientes, 50);
    lv_obj_set_height(ui_BtnPendientes, 50);
    lv_obj_set_x(ui_BtnPendientes, -184);
    lv_obj_set_y(ui_BtnPendientes, 5);
    lv_obj_set_align(ui_BtnPendientes, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnPendientes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPendientes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPendientes, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPendientes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPendientes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnPendientes, &ui_img_flecha50_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTareasExtras = lv_label_create(ui_ContTEBar);
    lv_obj_set_width(ui_lblTareasExtras, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTareasExtras, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTareasExtras, 15);
    lv_obj_set_y(ui_lblTareasExtras, 0);
    lv_obj_set_align(ui_lblTareasExtras, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTareasExtras, "TAREAS EXTRAS");
    lv_obj_set_style_text_font(ui_lblTareasExtras, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContTEContenido = lv_obj_create(ui_ContTareasExtras);
    lv_obj_remove_style_all(ui_ContTEContenido);
    lv_obj_set_width(ui_ContTEContenido, 240);
    lv_obj_set_height(ui_ContTEContenido, 160);
    lv_obj_set_flex_flow(ui_ContTEContenido, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContTEContenido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContTEContenido, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scroll_dir(ui_ContTEContenido, LV_DIR_VER);
    lv_obj_set_style_pad_row(ui_ContTEContenido, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContTEContenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPrueba1 = lv_btn_create(ui_ContTEContenido);
    lv_obj_set_width(ui_btnPrueba1, 240);
    lv_obj_set_height(ui_btnPrueba1, 20);
    lv_obj_set_align(ui_btnPrueba1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPrueba1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPrueba1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPrueba1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPrueba1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnPrueba1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPrueba1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_btnPrueba1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_btnPrueba1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btnPrueba1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "primero");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_btnPrueba1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label4, "segundo");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPrueba = lv_btn_create(ui_ContTEContenido);
    lv_obj_set_width(ui_btnPrueba, 240);
    lv_obj_set_height(ui_btnPrueba, 20);
    lv_obj_set_align(ui_btnPrueba, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPrueba, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPrueba, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnPrueba, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPrueba, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPrueba, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_btnPrueba, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_btnPrueba, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_btnPrueba);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label1, "primero");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_btnPrueba);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label2, "segundo");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCompletarTareaExtra = lv_btn_create(ui_PantallaTareasExtras);
    lv_obj_set_width(ui_BtnCompletarTareaExtra, 240);
    lv_obj_set_height(ui_BtnCompletarTareaExtra, 40);
    lv_obj_set_align(ui_BtnCompletarTareaExtra, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnCompletarTareaExtra, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BtnCompletarTareaExtra,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BtnCompletarTareaExtra, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblBtnCampletarTarea3 = lv_label_create(ui_BtnCompletarTareaExtra);
    lv_obj_set_width(ui_LblBtnCampletarTarea3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblBtnCampletarTarea3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblBtnCampletarTarea3, -1);
    lv_obj_set_y(ui_LblBtnCampletarTarea3, 1);
    lv_obj_set_align(ui_LblBtnCampletarTarea3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblBtnCampletarTarea3, "TAREA COMPLETADA");

    lv_obj_add_event_cb(ui_BtnPendientes, ui_event_BtnPendientes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCompletarTareaExtra, ui_event_BtnCompletarTareaExtra, LV_EVENT_ALL, NULL);

}
