###
POST http://192.168.100.47:2298/auth/reset/request
Content-Type: application/json

{
  "username": "Jona perrita"
}

### Paso 2: verificar código
POST http://192.168.100.47:2298/auth/reset/verify
Content-Type: application/json

{
  "username": "Jona perrita",
  "code": "778263"
}

### Paso 3: cambiar contraseña
POST http://192.168.100.47:2298/auth/reset/confirm
Content-Type: application/json

{
  "username": "Jona perrita",
  "new_password": "pass123"
}
